// src/components/shared/TheTermsOfServiceDialog.vue
<template>
  <v-dialog v-model="getIsTermsOfServiceDialogVisible" max-width="80%">
    <v-card>
      <v-card-title class="title">{{ $t('agreements.termsOfService.title') }}</v-card-title>
      <v-card-text v-html="content">
      </v-card-text>
      <v-card-actions>
        <v-spacer></v-spacer>
        <v-btn
          flat
          color="purple"
          @click="setIsTermsOfServiceDialogVisible(false)"
        >{{ $t('common.options.okButtonText') }}</v-btn>
      </v-card-actions>
    </v-card>
  </v-dialog>
</template>

<script>
import { mapGetters, mapMutations, mapActions } from 'vuex'

export default {
  name: 'TheTermsOfServiceDialog',
  data () {
    return {
      content: null,
      s3TermsOfUseFolder: 'terms-of-use'
    }
  },
  created () {
    console.log(`Current vue-i18n language is: ${this.$i18n.locale}`)
    this.$httpSitePoliciesStorage.get(`${this.s3TermsOfUseFolder}/${this.$i18n.locale}.html`).then(resp => {
      this.content = resp.data
    }).catch(err => {
      this.setNewSiteError(err.message || err)
    })
  },
  computed: {
    ...mapGetters({
      getIsTermsOfServiceDialogVisible: 'shared/getIsTermsOfServiceDialogVisible'
    })
  },
  methods: {
    ...mapMutations({
      setIsTermsOfServiceDialogVisible: 'shared/setIsTermsOfServiceDialogVisible'
    }),
    ...mapActions({
      setNewSiteError: 'shared/setNewSiteError'
    })
  }

}
</script>

// src/components/common/dialogs/TheTermsOfServiceDialog.tsx
import React, { useEffect, useState } from 'react'
import { BasicDialogProps } from 'types/props'
import {
  DialogContentText,
  Dialog,
  DialogTitle,
  DialogActions,
  Button,
  DialogContent
} from '@material-ui/core'
import { useTranslation } from 'react-i18next'
import { httpSitePoliciesStorage } from 'httpCall'
import i18n from 'i18n'
import { useSiteMessage } from 'hooks'

const TheTermsOfServiceDialog: React.FC<BasicDialogProps> = (props) => {
  const { onClose, open } = props
  const [body, setBody] = useState('')
  const { t } = useTranslation()
  const [, setSiteMessageData] = useSiteMessage()
  const s3TermsOfUseFolder = 'terms-of-use'

  useEffect(() => {
    httpSitePoliciesStorage
      .get(`${s3TermsOfUseFolder}/${i18n.language || 'en'}.html`)
      .then((resp) => {
        setBody(resp.data)
      })
      .catch((err) => {
        setSiteMessageData({
          show: true,
          type: 'error',
          timeout: null,
          text: err.message ?? err
        })
      })
  }, [setSiteMessageData])
  return (
    <Dialog open={open}>
      <DialogTitle>{t('agreements.termsOfService.title')}</DialogTitle>
      <DialogContent>
        <DialogContentText>{body}</DialogContentText>
      </DialogContent>
      <DialogActions>
        <Button variant="contained" color="primary" onClick={onClose}>
          {t('common.ok')}
        </Button>
      </DialogActions>
    </Dialog>
  )
}

export default TheTermsOfServiceDialog
